### ISSUE TITLE
Install govendor as an Available Tool

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/ansible-role-godev#10]
[govendor][govendor] is a popular tool for managing a vendored Go installation on a per-project basis, avoiding using `GOPATH` if necessary. It's a nice thing to have in a Go development environment, which is what this is.

#### Tasks

 - [ ] Define variable `govendor_version` and allow `latest` to be default.
 - [ ] Install the latest or a pinned version of `govendor` to somewhere which will ultimately be on users' `PATH`s.
 - [ ] Update README to document that `govendor` is provided and configurable.

 [govendor]: https://github.com/kardianos/govendor

**Comment by naftulikay** [comment]
Closed by #13.
