### ISSUE TITLE
Add Ability to Add More GOPATH Entries

### ISSUE THREAD

**Issue by naftulikay** [naftulikay/ansible-role-godev#9]
There should be a list variable which accepts additional paths to add verbatim to the `GOPATH` as defined in `/etc/profile.d/go.sh`.

#### Tasks

 - [ ] Define new variable `go_gopath_addtl_dirs` defaulting to `[]`.
 - [ ] Pipe in values into rendering of the profile shell file.
 - [ ] Document new variable in README.
